version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: slow-cooker
      POSTGRES_PASSWORD: postgres
    container_name: slowcooker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slow-cooker
    environment:
      - PORT=${PORT}
      - DATABASE_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - '.:/app'
    env_file:
      - '.env'
